#!/bin/bash

coan source -R -UWIN32 -UTSRM_WIN32 -U__GNUC__ -DZTS -UGNUPTH -DPTHREADS -DHAVE_SIGNAL_H -U__cplusplus -DHAVE_SIGPROCMASK -DHAVE_STDARG_H=1 -DTSRM_DEBUG=0 -UNETWARE -DTHR_DEBUG=0 -DZEND_DEBUG=0 -Fh,c ./
